/**
 * Stamp package.json's version into the places that cannot import it.
 *
 * package.json is the single source of truth. Three files need the value baked in:
 *
 *   src/version.ts        the Worker reports it at /api/health
 *   public/index.html     the PAGE's own version, so a stale shell is detectable
 *   public/sw.js          the cache name, so a new release cannot serve an old shell
 *
 * The page needs its own baked copy rather than just displaying what the API returns.
 * The service worker caches the shell, so an old page can be paired with a new Worker;
 * showing the server's version there would report "current" for a page that is not.
 * Comparing the two is what catches it.
 *
 * Run `npm run version:sync` after bumping the version. CI re-runs it and fails if
 * anything changes, so a bump can never be half-applied.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`package.json version "${version}" is not MAJOR.MINOR.PATCH`);
  process.exit(1);
}

const edits = [
  {
    file: "src/version.ts",
    write: () =>
      `// Generated by scripts/sync-version.mjs — do not edit.\n` +
      `// Source of truth is the "version" field in package.json.\n` +
      `export const VERSION = "${version}";\n`,
  },
  {
    file: "public/index.html",
    sub: [[/<meta name="app-version" content="[^"]*">/, `<meta name="app-version" content="${version}">`]],
  },
  {
    file: "public/sw.js",
    sub: [[/const CACHE = "note-shell-[^"]*";/, `const CACHE = "note-shell-${version}";`]],
  },
];

let changed = 0;
for (const e of edits) {
  const path = join(root, e.file);
  // A generated file legitimately may not exist yet on a fresh checkout.
  const before = existsSync(path) ? readFileSync(path, "utf8") : null;
  let after;

  if (e.write) {
    after = e.write();
  } else {
    if (before === null) {
      console.error(`${e.file}: missing`);
      process.exit(1);
    }
    after = before;
    for (const [pattern, replacement] of e.sub) {
      if (!pattern.test(after)) {
        console.error(`${e.file}: no match for ${pattern} — the anchor was renamed?`);
        process.exit(1);
      }
      after = after.replace(pattern, replacement);
    }
  }

  if (after !== before) {
    writeFileSync(path, after);
    console.log(`updated ${e.file} -> ${version}`);
    changed++;
  }
}

console.log(changed ? `synced ${changed} file(s) to ${version}` : `already at ${version}`);
